[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FourierTools = "b18b359b-aebc-45ac-a139-9c0ccbb2871e"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
NDTools = "98581153-e998-4eef-8d0d-5ec2c052313d"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PointSpreadFunctions = "e8810a93-244e-46c5-8da3-35c5dd956001"
StructuredIlluminationMicroscopy = "a7ea9a99-8dd4-4c38-9d41-c34fb0fe62c4"
SyntheticObjects = "e7028c27-0967-45e9-8fdb-dbc10ccb2b0a"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
View5D = "90d841e0-6953-4e90-9f3a-43681da8e949"
